### ISSUE TITLE
Grafici media dei dati

### ISSUE THREAD

**Issue by arn4** [paolini/covid19-charts#15]
Propongo l'aggiunta di una funzione che permette di rappresentare i dati mediati con i giorni precedenti in modo che il grafico risenta meno delle fluttuazioni giornaliere e dia un indicazione migliore sull'andamento. 

Purtroppo non ho modo di lavorarci, ma se qualcuno invece ha tempo e voglia sarebbe interessante.

**Comment by paolini** [comment]
C'è già questa funzione: basta selezionare "filter" e scegliere uno dei filtri. Il numero corrisponde al numero di giorni che vengono mediati (con pesi binomiali).
