### ISSUE TITLE
Filtro "flat 7" non è centrato

### ISSUE THREAD

**Issue by arn4** [paolini/covid19-charts#20]
Il filtro "flat 7" fa la media sui passati 7 giorni e non sui precedenti 3 e successivi 3 (oltre che quello in esame). Non so se è una cosa voluta, ma secondo me ci starebbe fare anche un filtro centrato, perchè altrimenti i grafici in questo modo vengono traslati rispetto ai dati veri. Ad esempio:
<img width="1100" alt="Screenshot 2020-10-04 at 12 57 00" src="https://user-images.githubusercontent.com/11385454/95015529-aecf4600-064d-11eb-8df1-2d6994a1d8a1.png">

Ci sarebbe il problema degli ultimi 3 punti che non avrebbero abbastanza dati a destra, ma ad esempio si potrebbe fare una media con meno punti (tipo 5, 3 ed 1).

**Comment by paolini** [comment]
Sì, la cosa è voluta: ho visto che normalmente la media su 7 giorni viene fatta in quel modo. Si può usare il filtro binomial_7 oppure non sarebbe difficile creare un nuovo filtro "flat_7_centered".

**Comment by arn4** [comment]
Ho implementato entrambe le cose. Ora faccio la pull request
