### ISSUE TITLE
Rapporto incremento positivi/casi testati sbagliato?

### ISSUE THREAD

**Issue by AlexFerretti1** [paolini/covid19-charts#22]
Caro Paolini,
innanzitutto grazie infinite per il tuo tool che a mia conoscenza è il più completo e maneggevole che si trovi in rete.
Ho notato che il valori del rapporto nuovi positivi/incremento casi testati a livello regionale con il filtro flat 7 non sono coerenti con i valori singoli di nuovi positivi e di incremento casi testati (entrambi flat 7). 
Per esempio: alla data del 14 ottobre i nuovi positivi in Piemonte risultano essere 454.7 e l'incremento casi testati risulta essere 3751.3, il loro rapporto dovrebbe quindi essere 12.12%.. e invece il valore del grafico nuovi positivi/incremento casi testati è 13,43%. 
Stessa cosa, anche se l'errore è minore, per la Campania: nuovi positivi 705.4, incremento casi testati 7690.9, rapporto atteso 9.172% e valore del grafico 9.241%
Se tolgo il filtro flat 7 da tutti i grafici, il rapporto risulta invece corretto. 
Magari c'è qualcosa che mi sfugge e quindi il rapporto corretto è quello del grafico, ma nella mia ignoranza ho pensato fosse opportuno segnalartelo.

Un caro saluto e ancora grazie per il tuo lavoro
Alessandro Ferretti

**Comment by paolini** [comment]
Caro Alessandro,
quando metti il filtro flat 7 ad un rapporto viene prima fatto il rapporto dei dati grezzi e poi viene fatta la media mobile su 7 giorni. Questo può dare un risultato diverso dal rapporto delle due medie mobili. Forse è questo il motivo della discrepanza che hai osservato...

**Comment by AlexFerretti1** [comment]
Sì, il motivo è sicuramente questo, la media dei rapporti in effetti è diversa dal rapporto delle medie.
Uno dei vantaggi del filtro flat 7 è che consente di avere la media settimanale, purtroppo però la media dei rapporti non ha significato statistico (o meglio, ha un significato diverso dal rapporto tra le medie): immagino però che inserire un ulteriore filtro dedicato ai rapporti che plotti il rapporto delle medie richieda una quantità di lavoro non trascurabile.. e io purtroppo non ho le competenze che mi consentano di aiutarti a farlo.  In ogni caso, grazie ancora!

**Comment by paolini** [comment]
Fare la modifica al codice non sarebbe così difficile. Il problema è che per come è ora organizzata l'interfaccia utente ho paura che una tale modifica potrebbe non essere chiara per tutti gli utenti. Visto che il filtro è a valle della scelta della quantità da plottare mi sembra che l'interpretazione più naturale è che venga applicato dopo aver fatto il rapporto. Se però è evidente che l'unica quantità con rilevanza statistica è il rapporto delle medie (invece che la media del rapporto) posso pensare di modificare il codice in quel senso. Io non sono esperto di statistica, provo a chiedere in giro per avere altre fonti.

**Comment by AlexFerretti1** [comment]
Ottimo, grazie di nuovo!

**Comment by paolini** [comment]
Ho implementato la richiesta.

**Comment by AlexFerretti1** [comment]
Grazie infinite, perfetto!

**Comment by AlexFerretti1** [comment]
Grazie per le ultime aggiunte tra le tipologie di grafici e per la customizzazione del periodo dei filtri!

Se posso suggerire delle ulteriori tipologie: per fare confronti tra regioni, sarebbe molto utile avere la possibilità di graficare l'incremento deceduti/popolazione, l'incremento tamponi/popolazione e l'incremento casi testati/popolazione.

Un caro saluto e sempre complimenti e grazie,
