### ISSUE TITLE
Province/State

### ISSUE THREAD

**Issue by G-Lorenz** [paolini/covid19-charts#28]
Ho notato ([qui](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/README.md)) che in time_series sono riportati i dati a livello di 'province/state' di fatto solo per gli Stati ex-coloniali (Olanda, Francia, UK...), e solo per quanto riguarda le dipendenze d'oltremare. Da come scrivono sembra che la cosa sia voluta, e che i dati mancanti siano visualizzabili solo nei [daily reports](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports).
Sinceramente non so se vale la pena andare a manipolare quei dati, però mi sembra interessante segnalarlo.

**Comment by paolini** [comment]
In effetti ci sono anche i files con le time series... le ho aggiunte come nuovo dataset. 4581a6d3f0a755bda9f0e73f8689c2851ff40889

**Comment by G-Lorenz** [comment]
Ho provato a creare le time series mancanti (con questo [programma](https://github.com/G-Lorenz/time_series-generator)). I dati che ho trovato si trovano [qui](https://github.com/G-Lorenz/covid19-time_series).
Credo possa essere interessante includerle nel sito, ovviamente come integrazione (e non sostituzione) dei dataset già presenti.
Segnalo comunque che, per motivi 'costruttivi', queste mie time series sono soggette a bug se alla JHU cambiano formato. In pratica se aggiungono o tolgono province possono esserci dei problemi, che quasi sempre si riducono alla perdita dei dati vecchi.
