### ISSUE TITLE
Strange fit

### ISSUE THREAD

**Issue by astrozot** [paolini/covid19-charts#29]
Ciao Manu,

ti segnalo un caso di [strano fit](https://paolini.github.io/covid19-charts/#options=%7B%22version%22%3A2%2C%22datasets%22%3A%5B%7B%22dataset%22%3A%22regioni%22%2C%22options%22%3A%7B%22filter%22%3A%22identity%207%22%2C%22column%22%3A%22terapia_intensiva%20%2F%20popolazione%22%2C%22value%22%3A%2222%22%2C%22value_name%22%3A%22P.A.%20Trento%22%7D%7D%5D%2C%22chart%22%3A%7B%22time_shift%22%3A%22%22%2C%22plot_type%22%3A%22linear%22%2C%22draw_fit%22%3Atrue%2C%22n_points%22%3A21%2C%22up_to_date%22%3A%22%22%2C%22axis_days_min%22%3A%22%22%2C%22axis_days_max%22%3A%22%22%2C%22axis_date_min%22%3A%22%22%2C%22axis_date_max%22%3A%22%22%2C%22axis_count_min%22%3A%22%22%2C%22axis_count_max%22%3A%22%22%2C%22fit_future_days%22%3A5%7D%2C%22epcalc_input%22%3A%7B%22N%22%3A60000000%2C%22I0%22%3A1%2C%22date0%22%3A%222020-01-01%22%2C%22R0%22%3A2.2%2C%22date1%22%3A%222020-04-09%22%2C%22R1%22%3A0.73%2C%22date2%22%3A%222020-06-01%22%2C%22R2%22%3A1.1%2C%22date3%22%3A%222020-05-01%22%2C%22D_incubation%22%3A5.2%2C%22D_infectious%22%3A2.9%2C%22CFR%22%3A0.02%2C%22Time_to_death%22%3A32%2C%22D_recovery_severe%22%3A28.6%2C%22D_recovery_mild%22%3A11.1%2C%22P_SEVERE%22%3A0.2%2C%22D_hospital_lag%22%3A5%7D%7D) nel codice: forse c'è un problema nel caso di modifiche del dato?

Ciao,
Marco

**Comment by paolini** [comment]
credo di averlo aggiustato, era solo un problema di visualizzazione

**Comment by astrozot** [comment]
Perfetto, grazie!
