### ISSUE TITLE
there is something strange..

### ISSUE THREAD

**Issue by AlexFerretti1** [paolini/covid19-charts#32]
![IMG_20210126_211702](https://user-images.githubusercontent.com/72895276/105900323-2b7e9980-601c-11eb-9373-ee773be488f6.jpg)
The last data on nuovi positivi seem to be incorrect.. maybe there is a problem with the dataset?

**Comment by paolini** [comment]
Maybe there was a problem in the DPC dataset. Now everything looks regular.
![Screenshot from 2021-01-28 07-51-28](https://user-images.githubusercontent.com/1196414/106101203-d6d33f80-613d-11eb-979e-b50eebaa2d89.png)
