### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by iannak1** [paolini/covid19-charts#4]

**Comment by iannak1** [comment]
Complimenti per l’ applicazione.
Vorrei segnalare però che ho appena provato per vedere i ricoverati su scala nazionale e vedo solo NaN.

**Comment by iannak1** [comment]
Aggiungo una cosa: l'errore continua a esserci se si guarda con safari per iPad. Ho provato ora con Chrome su iOS e funziona bene. Grazie

**Comment by ranma42** [comment]
Se è relativo alle date, potrebbe essere lo stesso problema risolto da https://github.com/paolini/covid19-charts/pull/2

**Comment by paolini** [comment]
@iannak1 puoi verificare se ora funziona?

**Comment by paolini** [comment]
Forse è stato risolto.
