### ISSUE TITLE
"P.A. Trento" mancante nella tendina delle Regioni

### ISSUE THREAD

**Issue by enricobattocchi** [paolini/covid19-charts#6]
Nella tendina delle Regioni è presente la Provincia Autonoma di Bolzano ma non quella di Trento. Quest'ultima è però presente nei dati per provincia.

![Schermata a 2020-03-27 08-35-13](https://user-images.githubusercontent.com/15989132/77732883-202a9e00-7006-11ea-90df-36243bf921cf.png)

Il problema si presenta sia su Firefox che su Chrome. La console Javascript non riporta alcun errore.
Credo che il problema sia che nei dati originali il `codice_regione` è 04 per entrambi, quindi `Table::get_column_distinct_pairs` in table.js non riesce a distinguerle. 

A conferma di ciò si vede che il dato della P.A. Bolzano dalla lista Regioni dà doppi valori (con curva spezzata): quelli di Trento e quelli di Bolzano.

![Screenshot_2020-03-27 covid-19 charts](https://user-images.githubusercontent.com/15989132/77734204-8fa18d00-7008-11ea-82e2-43986ddc939b.png)

**Comment by paolini** [comment]
Grazie!
